[build]
builder = "nixpacks"
buildCommand = "pip install -r backend/requirements.txt"

[deploy]
startCommand = "sh -c 'ls / && ls /app/ 2>/dev/null && ls /opt/ 2>/dev/null && pwd && ls'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
