import os

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MAPBOX_TOKEN = os.getenv("MAPBOX_TOKEN")
TINYFISH_API_KEY = os.getenv("TINYFISH_API_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
X_BEARER_TOKEN = os.getenv("X_BEARER_TOKEN")

# InsForge
INSFORGE_URL = os.getenv("INSFORGE_URL")
INSFORGE_API_KEY = os.getenv("INSFORGE_API_KEY")
INSFORGE_JWT_SECRET = os.getenv("INSFORGE_JWT_SECRET")
