import os

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
MAPBOX_TOKEN = os.getenv("MAPBOX_TOKEN")
TINYFISH_API_KEY = os.getenv("TINYFISH_API_KEY")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
